### ISSUE TITLE
Overview issue

### ISSUE THREAD

**Issue by grdw** [quintel/etlocal#4]
*Discussion points:*

- [ ] Authentication https://github.com/quintel/etlocal/issues/3
- [ ] Authorization and the types of users https://github.com/quintel/etlocal/issues/5
- [ ] Editing a local dataset https://github.com/quintel/etlocal/issues/7
- [ ] Editing a value of a local dataset https://github.com/quintel/etlocal/issues/6
- [ ] Reviewing changes https://github.com/quintel/etlocal/issues/8
- [ ] Hooking in the Refmanager https://github.com/quintel/etlocal/issues/9
- [ ] Exporting a dataset to be used for ETSource https://github.com/quintel/etlocal/issues/10
- [ ] Creating a new dataset https://github.com/quintel/etlocal/issues/11
- [ ] Approving an edit https://github.com/quintel/etlocal/issues/12
